--GIORGIO MASSARINI 0001164426

--ESERCIZIO 2.1
SELECT I1.codI AS CodI1, I2.CodI AS CodI2
FROM INTERVENTI I1, INTERVENTI I2 
WHERE I1.PID = I2.PID 
AND I1.DID = I2.DID
AND I1.NumDente = I2.NumDente
AND I1.NumDente IS NOT NULL 
AND I1.DATA < I2.DATA
AND NOT EXISTS ( SELECT *
			   FROM INTERVENTI I3
			   WHERE I3.PID = I1.PID
			   AND I3.NumDente=I1.NumDente
			   AND I1.DATA < I3.DATA
			   AND I3.DATA < I2.DATA );
			
			  
			  
--ESERCIZIO 2.2  
WITH CLIENTI_SOLO_DENTISTA( CLIENTE, DID) AS
(SELECT P.Cliente, MIN(I.DID)
 FROM PREVENTIVI P, INTERVENTI I, DENTISTI D
 WHERE D.DID = I.DID
 GROUP BY P.Cliente
 HAVING count(DISTINCT I.DID) = 1
),
CONTEGGI (DID, NumInterventi) AS 
(SELECT I.DID, COUNT(I.CodI)
 FROM PREVENTIVI P, INTERVENTI I, CLIENTI_SOLO_DENTISTA C
 WHERE P.PID = I.DID
 AND P.Cliente = C.Cliente
 AND I.DID = C.DID
 GROUP BY I.DID
)
SELECT D.DID, D.Nome, COALESCE(C.NumINterventi, 0 ) AS NumInterventi
FROM DENTISTI D
LEFT JOIN CONTEGGI C ON D.DID=C.DID;

 