--GIORGIO MASSARINI 0001164426

--ESERCIZIO 4.1
CREATE TABLE E1(
	K1 int NOT NULL PRIMARY KEY,
	A INT NOT NULL,
	TIPO23 SMALLINT NOT NULL CHECK (TIPO23 IN (1,2,3)),
	B int,
	c int,
	K1R1 INT REFERENCES E1,
	CONSTRAINT E2_CHECK check((TIPO23 = 1 AND B IS NULL) OR (TIPO23 IN (2,3) AND B IS NOT NULL)),
	CONSTRAINT R1_CHECK CHECK((TIPO23 <> 3 AND K1R1 IS NULL ) OR (TIPO23=3 AND K1R1 IS NOT NULL))
	);
	
CREATE TABLE R2(
	K1E1 INT NOT NULL REFERENCES E1,
	K1E2 INT NOT NULL REFERENCES E1,
	D INT,
	PRIMARY KEY(K1E1, K1E2)
	);


--ESERCIZIO 4.2
CREATE OR REPLACE TRIGGER R2_E2
BEFORE INSERT ON R2
REFERENCING NEW AS N
FOR EACH ROW
WHEN (EXISTS (SELECT *
			  FROM E1
			  WHERE N.K1E2=E1.K1
			  AND E1.TIPO23=1
			 ))
SIGNAL SQLSTATE'70001'('La Tupla referenzia una tupla che non appartiene a E2');


	
CREATE OR REPLACE TRIGGER PUNTO_C
BEFORE INSERT ON R2
REFERENCING NEW AS N
FOR EACH ROW
WHEN (EXISTS (SELECT *
			  FROM E1 E3, E1 X
			  WHERE E3.K1 = N.K1E2
			  AND E3.TIPO23 = 3
			  AND X.K1= E3.K1R1
			  AND X.A + E3.C >10 ))
SIGNAL SQLSTATE'70002'('La Tupla inserita in R2 non rispetta il vincolo del punto C');






